name = "SPGBox"
uuid = "bf97046b-3e66-4aa0-9aed-26efb7fac769"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br>"]
version = "0.3.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
